About Dataset
This dataset simulates a set of key economic, social, and environmental indicators for 20 countries over the period from 2010 to 2019.
The dataset is designed to reflect typical World Bank metrics, which are used for analysis, policy-making, and forecasting. It includes the following variables:

Country Name: The country for which the data is recorded.
Year: The specific year of the observation (from 2010 to 2019).
GDP (USD): Gross Domestic Product in billions of US dollars, indicating the economic output of a country.
Population: The total population of the country in millions.
Life Expectancy (in years): The average life expectancy at birth for the country’s population.
Unemployment Rate (%): The percentage of the total labor force that is unemployed but actively seeking employment.
CO2 Emissions (metric tons per capita): The per capita carbon dioxide emissions, reflecting environmental impact.
Access to Electricity (% of population): The percentage of the population with access to electricity, representing infrastructure development.
Country:

Description: Name of the country for which the data is recorded.
Data Type: String
Example: "United States", "India", "Brazil"
Year:

Description: The year in which the data is observed.
Data Type: Integer
Range: 2010 to 2019
Example: 2012, 2015
GDP (USD):

Description: The Gross Domestic Product of the country in billions of US dollars, indicating the economic output.
Data Type: Float (billions of USD)
Example: 14200.56 (represents 14,200.56 billion USD)
Population:

Description: The total population of the country in millions.
Data Type: Float (millions of people)
Example: 331.42 (represents 331.42 million people)
Life Expectancy (in years):

Description: The average number of years a newborn is expected to live, assuming that current mortality rates remain constant throughout their life.
Data Type: Float (years)
Range: Typically between 50 and 85 years
Example: 78.5 years
Unemployment Rate (%):

Description: The percentage of the total labor force that is unemployed but actively seeking employment.
Data Type: Float (percentage)
Range: Typically between 2% and 25%
Example: 6.25%
CO2 Emissions (metric tons per capita):

Description: The amount of carbon dioxide emissions per person in the country, measured in metric tons.
Data Type: Float (metric tons)
Range: Typically between 0.5 and 20 metric tons per capita
Example: 4.32 metric tons per capita
Access to Electricity (%):

Description: The percentage of the population with access to electricity.
Data Type: Float (percentage)
Range: Typically between 50% and 100%
Example: 95.7%

In [51]:
import pandas as pd
import janitor
import re
import plotly.express as px

# Data import

In [52]:
#with open("../data/world_bank_dataset.csv", 'r') as file:
#    colnames = ['country', 'year', 'gdp', 'population', 'life_expectancy', 'unemployment_rate', 'co2', 'access_electricity']
#    data_word_bank = pd.read_csv(file, names=colnames,header=0)

with open("../data/World_Development.xlsx", 'rb') as file:
    data_word_dev = pd.read_excel(file)

data_word_dev.head()

,Country Name,Country Code,Time,Time Code,Access to electricity (% of population) [EG.ELC.ACCS.ZS],Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS],"Automated teller machines (ATMs) (per 100,000 adults) [FB.ATM.TOTL.P5]","Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]","Claims on central government, etc. (% GDP) [FS.AST.CGOV.GD.ZS]","Commercial bank branches (per 100,000 adults) [FB.CBK.BRCH.P5]",...,Surface area (sq. km) [AG.SRF.TOTL.K2],"Survival to age 65, female (% of cohort) [SP.DYN.TO65.FE.ZS]","Survival to age 65, male (% of cohort) [SP.DYN.TO65.MA.ZS]",Trade (% of GDP) [NE.TRD.GNFS.ZS],UHC service coverage index [SH.UHC.SRVS.CV.XD],"Unemployment, female (% of female labor force) (modeled ILO estimate) [SL.UEM.TOTL.FE.ZS]","Unemployment, male (% of male labor force) (modeled ILO estimate) [SL.UEM.TOTL.MA.ZS]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS],Voice and Accountability: Estimate [VA.EST]
0,Afghanistan,AFG,1960,YR1960,NaN,NaN,NaN,50.340,5.016529,NaN,...,NaN,21.190631,17.743034,11.157027,NaN,NaN,NaN,NaN,8.401,NaN
1,Afghanistan,AFG,1961,YR1961,NaN,NaN,NaN,50.443,9.388664,NaN,...,652860.0,21.819029,18.350272,12.550610,NaN,NaN,NaN,NaN,8.684,NaN
2,Afghanistan,AFG,1962,YR1962,NaN,NaN,NaN,50.570,12.093496,NaN,...,652860.0,22.397017,18.878496,14.227644,NaN,NaN,NaN,NaN,8.976,NaN
3,Afghanistan,AFG,1963,YR1963,NaN,NaN,NaN,50.703,10.857987,NaN,...,652860.0,22.973204,19.395900,26.035511,NaN,NaN,NaN,NaN,9.276,NaN
4,Afghanistan,AFG,1964,YR1964,NaN,NaN,NaN,50.831,13.899999,NaN,...,652860.0,23.546267,19.941843,26.944448,NaN,NaN,NaN,NaN,9.586,NaN

In [53]:
data_word_dev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16960 entries, 0 to 16959
Data columns (total 63 columns):
 #   Column                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                        --------------  -----
 0   Country Name                                                                                                  16960 non-null  object
 1   Country Code                                                                                                  16960 non-null  object
 2   Time                                                                                                          16960 non-null  int64
 3   Time Code                                                                                                     16960 non-null  object
 4   Access to electricity (% of population) [EG.ELC.ACCS.ZS]                                                      7348 non-null   float64
 5   Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS]                                        12883 non-null  float64
 6   Automated teller machines (ATMs) (per 100,000 adults) [FB.ATM.TOTL.P5]                                        3812 non-null   float64
 7   Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]                                                         16300 non-null  float64
 8   Claims on central government, etc. (% GDP) [FS.AST.CGOV.GD.ZS]                                                10853 non-null  float64
 9   Commercial bank branches (per 100,000 adults) [FB.CBK.BRCH.P5]                                                3988 non-null   float64
 10  Compulsory education, duration (years) [SE.COM.DURS]                                                          6071 non-null   float64
 11  Control of Corruption: Estimate [CC.EST]                                                                      4783 non-null   float64
 12  Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]                                                         16282 non-null  float64
 13  Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS]                                 5154 non-null   float64
 14  Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD]                   5153 non-null   float64
 15  Domestic general government health expenditure per capita, PPP (current international $) [SH.XPD.GHED.PP.CD]  5152 non-null   float64
 16  Employment to population ratio, 15+, female (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.FE.ZS]                 7752 non-null   float64
 17  Employment to population ratio, 15+, male (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.MA.ZS]                   7752 non-null   float64
 18  Employment to population ratio, 15+, total (%) (modeled ILO estimate) [SL.EMP.TOTL.SP.ZS]                     7752 non-null   float64
 19  Exports of goods and services (BoP, current US$) [BX.GSR.GNFS.CD]                                             9128 non-null   float64
 20  External balance on goods and services (% of GDP) [NE.RSB.GNFS.ZS]                                            10707 non-null  float64
 21  Fixed broadband subscriptions (per 100 people) [IT.NET.BBND.P2]                                               4919 non-null   float64
 22  Foreign direct investment, net inflows (% of GDP) [BX.KLT.DINV.WD.GD.ZS]                                      10982 non-null  float64
 23  Foreign direct investment, net inflows (BoP, current US$) [BX.KLT.DINV.CD.WD]                                 11679 non-null  float64
 24  GDP (current US$) [NY.GDP.MKTP.CD]                                                                            13178 non-null  float64
 25  GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]                                                                     12746 non-null  float64
 26  GDP per capita (current US$) [NY.GDP.PCAP.CD]                                                                 13182 non-null  float64
 27  GDP per capita growth (annual %) [NY.GDP.PCAP.KD.ZG]                                                          12743 non-null  float64
 28  GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]                                             7836 non-null   float64
 29  GDP, PPP (current international $) [NY.GDP.MKTP.PP.CD]                                                        7836 non-null   float64
 30  General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]                                  10434 non-null  float64
 31  GNI (current US$) [NY.GNP.MKTP.CD]                                                                            11951 non-null  float64
 32  GNI per capita, PPP (current international $) [NY.GNP.PCAP.PP.CD]                                             7510 non-null   float64
 33  GNI, PPP (current international $) [NY.GNP.MKTP.PP.CD]                                                        7510 non-null   float64
 34  Government Effectiveness: Estimate [GE.EST]                                                                   4759 non-null   float64
 35  Individuals using the Internet (% of population) [IT.NET.USER.ZS]                                             8044 non-null   float64
 36  Inflation, GDP deflator (annual %) [NY.GDP.DEFL.KD.ZG]                                                        12635 non-null  float64
 37  Labor force, total [SL.TLF.TOTL.IN]                                                                           7752 non-null   float64
 38  Life expectancy at birth, female (years) [SP.DYN.LE00.FE.IN]                                                  16124 non-null  float64
 39  Life expectancy at birth, male (years) [SP.DYN.LE00.MA.IN]                                                    16124 non-null  float64
 40  Life expectancy at birth, total (years) [SP.DYN.LE00.IN]                                                      16124 non-null  float64
 41  Mobile cellular subscriptions (per 100 people) [IT.CEL.SETS.P2]                                               12662 non-null  float64
 42  Net migration [SM.POP.NETM]                                                                                   16960 non-null  int64
 43  People using at least basic drinking water services (% of population) [SH.H2O.BASW.ZS]                        5867 non-null   float64
 44  People using at least basic sanitation services (% of population) [SH.STA.BASS.ZS]                            5891 non-null   float64
 45  Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]                                      4820 non-null   float64
 46  Population ages 15-64, total [SP.POP.1564.TO]                                                                 16665 non-null  float64
 47  Population density (people per sq. km of land area) [EN.POP.DNST]                                             14901 non-null  float64
 48  Population growth (annual %) [SP.POP.GROW]                                                                    16398 non-null  float64
 49  Population, total [SP.POP.TOTL]                                                                               16665 non-null  float64
 50  Prevalence of undernourishment (% of population) [SN.ITK.DEFC.ZS]                                             4568 non-null   float64
 51  Regulatory Quality: Estimate [RQ.EST]                                                                         4761 non-null   float64
 52  Rule of Law: Estimate [RL.EST]                                                                                4873 non-null   float64
 53  Surface area (sq. km) [AG.SRF.TOTL.K2]                                                                        15932 non-null  float64
 54  Survival to age 65, female (% of cohort) [SP.DYN.TO65.FE.ZS]                                                  16695 non-null  float64
 55  Survival to age 65, male (% of cohort) [SP.DYN.TO65.MA.ZS]                                                    16695 non-null  float64
 56  Trade (% of GDP) [NE.TRD.GNFS.ZS]                                                                             10698 non-null  float64
 57  UHC service coverage index [SH.UHC.SRVS.CV.XD]                                                                1428 non-null   float64
 58  Unemployment, female (% of female labor force) (modeled ILO estimate) [SL.UEM.TOTL.FE.ZS]                     7752 non-null   float64
 59  Unemployment, male (% of male labor force) (modeled ILO estimate) [SL.UEM.TOTL.MA.ZS]                         7752 non-null   float64
 60  Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]                          7752 non-null   float64
 61  Urban population (% of total population) [SP.URB.TOTL.IN.ZS]                                                  16569 non-null  float64
 62  Voice and Accountability: Estimate [VA.EST]                                                                   4850 non-null   float64
dtypes: float64(58), int64(2), object(3)
memory usage: 8.2+ MB

In [54]:
data_word_dev.describe()

,Time,Access to electricity (% of population) [EG.ELC.ACCS.ZS],Adjusted savings: education expenditure (% of GNI) [NY.ADJ.AEDU.GN.ZS],"Automated teller machines (ATMs) (per 100,000 adults) [FB.ATM.TOTL.P5]","Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]","Claims on central government, etc. (% GDP) [FS.AST.CGOV.GD.ZS]","Commercial bank branches (per 100,000 adults) [FB.CBK.BRCH.P5]","Compulsory education, duration (years) [SE.COM.DURS]",Control of Corruption: Estimate [CC.EST],"Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]",...,Surface area (sq. km) [AG.SRF.TOTL.K2],"Survival to age 65, female (% of cohort) [SP.DYN.TO65.FE.ZS]","Survival to age 65, male (% of cohort) [SP.DYN.TO65.MA.ZS]",Trade (% of GDP) [NE.TRD.GNFS.ZS],UHC service coverage index [SH.UHC.SRVS.CV.XD],"Unemployment, female (% of female labor force) (modeled ILO estimate) [SL.UEM.TOTL.FE.ZS]","Unemployment, male (% of male labor force) (modeled ILO estimate) [SL.UEM.TOTL.MA.ZS]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS],Voice and Accountability: Estimate [VA.EST]
count,16960.000000,7348.000000,12883.000000,3812.000000,16300.000000,10853.000000,3988.000000,6071.000000,4783.000000,16282.000000,...,1.593200e+04,16695.000000,16695.000000,10698.000000,1428.000000,7752.000000,7752.000000,7752.000000,16569.000000,4850.000000
mean,1991.500000,80.758176,4.041467,42.080247,28.043431,8.631726,16.746426,9.436831,-0.024874,10.455614,...,5.394758e+06,69.582992,59.627697,72.502845,59.551821,9.159337,7.353507,7.919577,50.236006,-0.021062
std,18.473498,28.745226,2.460375,44.334681,12.876307,18.330783,19.170935,2.187316,1.000047,5.334836,...,1.556152e+07,17.170751,16.344252,51.003434,18.914353,6.951680,5.102000,5.515419,24.771559,0.998757
min,1960.000000,0.533899,0.247919,0.000000,4.400000,-192.529040,0.040000,0.000000,-1.936706,0.795000,...,2.027000e+00,0.046306,0.000668,0.020999,11.000000,0.147000,0.045000,0.100000,2.077000,-2.313395
25%,1975.750000,68.435427,2.700000,8.535000,16.300000,0.916163,4.958750,8.500000,-0.791694,6.965136,...,2.104000e+04,57.337480,47.880048,41.257562,45.000000,4.310750,3.987750,4.152000,29.973978,-0.850328
50%,1991.500000,98.290939,3.743548,31.415000,26.818501,6.973541,11.800000,9.000000,-0.253887,9.178311,...,2.076000e+05,73.822139,61.516574,60.398081,63.000000,6.847948,6.004749,6.388657,48.781000,0.020768
75%,2007.250000,100.000000,4.816466,58.337500,39.579250,14.210991,22.680000,11.000000,0.666176,12.375000,...,1.267000e+06,83.394009,71.925137,91.441860,76.000000,12.365250,9.444972,10.410500,69.524000,0.884255
max,2023.000000,100.000000,68.152930,324.170000,58.121000,272.697203,242.780000,17.000000,2.459118,103.534000,...,1.404869e+08,96.676574,94.688532,863.195099,91.000000,44.638000,36.963000,38.800000,100.000000,1.800992

In [55]:

data_word_dev.clean_names()

,country_name,country_code,time,time_code,access_to_electricity_%_of_population_[eg_elc_accs_zs],adjusted_savings_education_expenditure_%_of_gni_[ny_adj_aedu_gn_zs],automated_teller_machines_atms_per_100_000_adults_[fb_atm_totl_p5],birth_rate_crude_per_1_000_people_[sp_dyn_cbrt_in],claims_on_central_government_etc_%_gdp_[fs_ast_cgov_gd_zs],commercial_bank_branches_per_100_000_adults_[fb_cbk_brch_p5],...,surface_area_sq_km_[ag_srf_totl_k2],survival_to_age_65_female_%_of_cohort_[sp_dyn_to65_fe_zs],survival_to_age_65_male_%_of_cohort_[sp_dyn_to65_ma_zs],trade_%_of_gdp_[ne_trd_gnfs_zs],uhc_service_coverage_index_[sh_uhc_srvs_cv_xd],unemployment_female_%_of_female_labor_force_modeled_ilo_estimate_[sl_uem_totl_fe_zs],unemployment_male_%_of_male_labor_force_modeled_ilo_estimate_[sl_uem_totl_ma_zs],unemployment_total_%_of_total_labor_force_modeled_ilo_estimate_[sl_uem_totl_zs],urban_population_%_of_total_population_[sp_urb_totl_in_zs],voice_and_accountability_estimate_[va_est]
0,Afghanistan,AFG,1960,YR1960,NaN,NaN,NaN,50.340000,5.016529,NaN,...,NaN,21.190631,17.743034,11.157027,NaN,NaN,NaN,NaN,8.401000,NaN
1,Afghanistan,AFG,1961,YR1961,NaN,NaN,NaN,50.443000,9.388664,NaN,...,6.528600e+05,21.819029,18.350272,12.550610,NaN,NaN,NaN,NaN,8.684000,NaN
2,Afghanistan,AFG,1962,YR1962,NaN,NaN,NaN,50.570000,12.093496,NaN,...,6.528600e+05,22.397017,18.878496,14.227644,NaN,NaN,NaN,NaN,8.976000,NaN
3,Afghanistan,AFG,1963,YR1963,NaN,NaN,NaN,50.703000,10.857987,NaN,...,6.528600e+05,22.973204,19.395900,26.035511,NaN,NaN,NaN,NaN,9.276000,NaN
4,Afghanistan,AFG,1964,YR1964,NaN,NaN,NaN,50.831000,13.899999,NaN,...,6.528600e+05,23.546267,19.941843,26.944448,NaN,NaN,NaN,NaN,9.586000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16955,World,WLD,2019,YR2019,90.193562,3.864939,40.73,17.817692,32.671524,10.995,...,1.347256e+08,81.938009,73.343691,56.497579,68.0,5.681180,5.532497,5.591542,55.627911,NaN
16956,World,WLD,2020,YR2020,90.482703,3.832505,41.24,17.226614,40.189099,10.590,...,1.347320e+08,80.770399,71.668728,52.433936,NaN,6.602767,6.603577,6.603279,56.061754,NaN
16957,World,WLD,2021,YR2021,91.414096,3.824791,39.49,16.942325,41.642027,11.180,...,1.404869e+08,79.028974,69.531014,56.811601,68.0,6.210113,5.967561,6.064105,56.476512,NaN
16958,World,WLD,2022,YR2022,NaN,NaN,NaN,16.649626,32.473212,NaN,...,NaN,79.980073,70.860986,62.563549,NaN,5.512472,5.106076,5.267477,56.899080,NaN
16959,World,WLD,2023,YR2023,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.264264,5.028603,5.123161,NaN,NaN

## Clean colnames

In [56]:
data_word_dev.columns = [re.split(r'\(|\[|\:', col)[0].strip() for col in data_word_dev.columns]
data_word_dev = data_word_dev.clean_names()

In [57]:
data_word_dev.columns

Index(['country_name', 'country_code', 'time', 'time_code',
       'access_to_electricity', 'adjusted_savings',
       'automated_teller_machines', 'birth_rate_crude',
       'claims_on_central_government_etc_', 'commercial_bank_branches',
       'compulsory_education_duration', 'control_of_corruption',
       'death_rate_crude', 'domestic_general_government_health_expenditure',
       'domestic_general_government_health_expenditure_per_capita',
       'domestic_general_government_health_expenditure_per_capita_ppp',
       'employment_to_population_ratio_15+_female',
       'employment_to_population_ratio_15+_male',
       'employment_to_population_ratio_15+_total',
       'exports_of_goods_and_services',
       'external_balance_on_goods_and_services',
       'fixed_broadband_subscriptions',
       'foreign_direct_investment_net_inflows',
       'foreign_direct_investment_net_inflows', 'gdp', 'gdp_growth',
       'gdp_per_capita', 'gdp_per_capita_growth', 'gdp_per_capita_ppp',
       'gdp_ppp', 'general_government_final_consumption_expenditure', 'gni',
       'gni_per_capita_ppp', 'gni_ppp', 'government_effectiveness',
       'individuals_using_the_internet', 'inflation_gdp_deflator',
       'labor_force_total', 'life_expectancy_at_birth_female',
       'life_expectancy_at_birth_male', 'life_expectancy_at_birth_total',
       'mobile_cellular_subscriptions', 'net_migration',
       'people_using_at_least_basic_drinking_water_services',
       'people_using_at_least_basic_sanitation_services',
       'political_stability_and_absence_of_violence_terrorism',
       'population_ages_15_64_total', 'population_density',
       'population_growth', 'population_total',
       'prevalence_of_undernourishment', 'regulatory_quality', 'rule_of_law',
       'surface_area', 'survival_to_age_65_female', 'survival_to_age_65_male',
       'trade', 'uhc_service_coverage_index', 'unemployment_female',
       'unemployment_male', 'unemployment_total', 'urban_population',
       'voice_and_accountability'],
      dtype='object')